# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ab38443850676d94339da215c8fd0ab11444cea3cbd7715336255e59051c02f78badded2674eab3236cd694eb533f660f6926aff30e4a381e28b16e0b5ee41

test:
  secret_key_base: 7665f7ad46dc215ecde27623c48731923139525574a7696fab4e80e67d0e7b3226b897c6d0516be31717eebb335d5059e5cc0bcb4bc23d212b4529c98daeef27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
